### ISSUE TITLE
defaults/main.yml is overwritten by vars/main.yml

### ISSUE THREAD

**Issue by pbrooks** [Aplyca/ansible-role-s3fs#3]
Attempting to install s3 deps, the following error is displayed:

task path: /private/etc/ansible/roles/Aplyca.s3fs/tasks/setup.yml:11
fatal: []: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'source'"}

This is due to vars being of a higher prescedence to defaults.

**Comment by mauricios** [comment]
@pbrooks Thanks for trying this role and reporting issues.

You should use `merge` hash behaviour for variables (like dictionaries in Python). You can set this configuration by adding the setting `hash_behaviour=merge` to the `ansible.cfg` file which should be placed in the same directory where you are executing ansible-playbook command. 

See the docs for more info: http://docs.ansible.com/ansible/intro_configuration.html#hash-behaviour or see the example here: https://github.com/Aplyca/ansible-role-s3fs/blob/master/ansible.cfg

**Comment by pbrooks** [comment]
@mauricios Thanks for this information and for amending the docs. I've just got round to improving my playbook to reflect your advice :)
